### ISSUE TITLE
Authentication using Private Key fails

### ISSUE THREAD

**Issue by nickpiggott** [spodskubka/RemoteTerminal#22]
Since v1.90, connections that are configured to use a specific Private Key fail. The window outline turns red, there is an outline of a green cursor, but no connection is made.

If the connection is configured to use Private Key Agent, and all the Private Keys added to the Private Key Agent, authentication succeeds.

I have tested across multiple connections configured to use Private Key, to a variety of different servers, and with three different private keys - all combinations fail.

**Comment by spodskubka** [comment]
@nickpiggott Thanks for opening this issue!
Someone else already reported this via email but I haven't gotten around to opening an issue or investigating the bug yet.

I will try to fix this over the weekend. Sorry for the troubles!

**Comment by scott-cothrell** [comment]
pasting email contents:

To be clear, it is ssh with pre-shared keys that is not working.  SSH to a login prompt works fine.  I uninstalled/reinstalled from the MS Store and got the same results.

With respect to key based automatic logins, if I use the key agent with the proper key selected and loaded, I get the following:

Username: scothrel
Performing private key agent authentication.
User cannot be authenticated.
Please load the necessary private key(s) into the private key agent.

Press Ctrl+R to reconnect.


If I use the other method and associate the key with the login directly, I get no response…just a red bordered, blank screen.

**Comment by spodskubka** [comment]
Problem found, bugfix incoming.

**Comment by schnubb** [comment]
great! any schedule for a release?

**Comment by spodskubka** [comment]
The update was submitted for certification about 20 minutes after this issue was closed.
In my experience the certification usually takes one to two days.

**Comment by spodskubka** [comment]
Certification is done, update packages should be available. If you haven't gotten the update automatically yet use the Windows Store App to check for updates manually.

**Comment by scott-cothrell** [comment]
Auto updated today.  Fix verified.  Thank you for the quick turn around!!

**Comment by nickpiggott** [comment]
+1

**Comment by spodskubka** [comment]
You're welcome. But the bug shouldn't have been there in the first place.

I am going to introduce some testing procedures, maybe work on some automated integration tests, to catch such bugs before doing a release. Until now I had nothing like it, and that's bad, I know that.
