### ISSUE TITLE
Multiple connections with tabs

### ISSUE THREAD

**Issue by oddtwelve** [spodskubka/RemoteTerminal#27]
Not sure, if this a bug report or feature request, but mouse was useless when I first installed the app. Simple test - I just wanted to choose panels in Midnight Commander.

If you'd support mouse - that'd be a flawless app!

Also, how about supporting multiple connections with tabs?

**Comment by spodskubka** [comment]
See #11 for multiple visible terminals side by side.

Other than that multiple open terminals are already possible, you have to open one, then navigate back using the top app bar (use the right mouse button to make it visible). You are back at the connection list and can open another connection now.
From now on the top app bar will hold all open terminal windows and you can switch between them.
