### ISSUE TITLE
Can not connect to openssh server 7.2

### ISSUE THREAD

**Issue by pitsi** [spodskubka/RemoteTerminal#3]
Since I upgraded my server to openssh version 7.2 (from 7.1), your client can not connect. The log on the server says this

http://paste.debian.net/416454/

so I assume it has to do with the values of (1024, 1024, 1024) that is hardcoded in the app, while the server requires (2048, 2048, 1024)

**Comment by CanadianJeff** [comment]
that paste is 404

**Comment by pitsi** [comment]
I opened the issue like... 6+ months ago! Since then, even openssh got a new major version (7.2 > 7.3).
The default (and maximum) time debian's pastebin can host stuff is 90 days, so yes, it was deleted!

I have sold my windows 8.1 tablet since then. Your app was one of my most used ones that did not work anymore, and there were no alternatives in the store so... I moved to androd.
So, I have no way to repost any logs now. However, if you do plan to fix it soon, I will search my posts at a forum where I discussed the problem with more experienced users to find a log of that time. Keep in mind it will be of openssh 7.2, so there may be new problems in openssh 7.3.

**Comment by pitsi** [comment]
There you go

http://paste.debian.net/877580/

Inside all that mess, the important line is
[code]Mar 16 08:38:50 mpriki sshd[832]: fatal: mm_answer_moduli: bad parameters: 2048 2048 1024[/code]

**Comment by CanadianJeff** [comment]
it looks like someone forked this repo and might have fixed it so you could probley close this issue

**Comment by pitsi** [comment]
Is there a link for the forked repo or for the app inside the app store? It has to be w8.1 compatible obviously and not a universal app for w10...

**Comment by pitsi** [comment]
I assume you mean this. 
https://github.com/kexanie/RemoteTerminal/

As I see in the commits section, it does have a fix for openssh 7.2 and newer. It is even advertised on the app's page on windows store!

> Remote Terminal 2 is a fork of Remote Terminal, which is originally created by spodskubka. Since the original project is no longer maintained. I republished it as Remote Terminal 2 to support OpenSsh 7.2 or higher.

It seems we can mark this issue as closed now. Too bad I am not on a windows tablet anymore to test it.

**Comment by spodskubka** [comment]
I will incorporate the changes implemented by @kexanie into the Remote Terminal code base.
Additionally I will refine them to match the current SSH.NET implementation.

**Comment by spodskubka** [comment]
Implemented in #8 if somebody wants to take a look.
Will merge when nobody responds during the next days.
