### ISSUE TITLE
hide mouse on fullscreen

### ISSUE THREAD

**Issue by CanadianJeff** [spodskubka/RemoteTerminal#5]
is such a thing possible?
I am on windows 10 64bit Version 1607 (Build 14393.222)

**Comment by spodskubka** [comment]
I will try to get this into the next release which I am planning for the next few days.

**Comment by spodskubka** [comment]
This will have to wait for a release after 1.9.0, which I have just submitted for certification.

**Comment by CanadianJeff** [comment]
closing due to age feel free to reopen
