### ISSUE TITLE
Outside the Valid Range

### ISSUE THREAD

**Issue by qops1981** [spodskubka/RemoteTerminal#7]
The moment I try to open a connection to an SSH endpoint I simply get in duplicate: "The operation attempt to access data outside the valid range" on a black background with a green outlined cursor rectangle.
I have not tested any other kind of connection, but I mainly use SSH.

**Comment by spodskubka** [comment]
This is a duplicate of #3, which will be fixed soon.

**Comment by spodskubka** [comment]
@qops1981 FYI: #3 was already closed but I re-opened it since the issue was not resolved in this repository. Thanks for reporting it anyway!
